# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSNT_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainlayout_1 = QtWidgets.QHBoxLayout()
        self.mainlayout_1.setContentsMargins(5, 5, 5, 5)
        self.mainlayout_1.setSpacing(5)
        self.mainlayout_1.setObjectName("mainlayout_1")
        self.tl_frame = QtWidgets.QFrame(self.centralwidget)
        self.tl_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tl_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tl_frame.setObjectName("tl_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tl_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_resource = QtWidgets.QLabel(self.tl_frame)
        self.label_resource.setObjectName("label_resource")
        self.verticalLayout_4.addWidget(self.label_resource)
        self.textEdit_resource = QtWidgets.QTextEdit(self.tl_frame)
        self.textEdit_resource.setObjectName("textEdit_resource")
        self.verticalLayout_4.addWidget(self.textEdit_resource)
        self.pushButton_clear_resource = QtWidgets.QPushButton(self.tl_frame)
        self.pushButton_clear_resource.setObjectName("pushButton_clear_resource")
        self.verticalLayout_4.addWidget(self.pushButton_clear_resource)
        self.mainlayout_1.addWidget(self.tl_frame)
        self.tm_frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.tm_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tm_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tm_frame_1.setObjectName("tm_frame_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tm_frame_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tm_frame_2 = QtWidgets.QFrame(self.tm_frame_1)
        self.tm_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tm_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tm_frame_2.setObjectName("tm_frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tm_frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_shiftLevel = QtWidgets.QLabel(self.tm_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_shiftLevel.sizePolicy().hasHeightForWidth())
        self.label_shiftLevel.setSizePolicy(sizePolicy)
        self.label_shiftLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shiftLevel.setIndent(0)
        self.label_shiftLevel.setObjectName("label_shiftLevel")
        self.horizontalLayout_4.addWidget(self.label_shiftLevel)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tm_frame_2)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addWidget(self.tm_frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_encode = QtWidgets.QPushButton(self.tm_frame_1)
        self.pushButton_encode.setObjectName("pushButton_encode")
        self.verticalLayout_3.addWidget(self.pushButton_encode)
        self.pushButton_decode = QtWidgets.QPushButton(self.tm_frame_1)
        self.pushButton_decode.setObjectName("pushButton_decode")
        self.verticalLayout_3.addWidget(self.pushButton_decode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.mainlayout_1.addWidget(self.tm_frame_1)
        self.tr_frame = QtWidgets.QFrame(self.centralwidget)
        self.tr_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tr_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tr_frame.setObjectName("tr_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tr_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_convert = QtWidgets.QLabel(self.tr_frame)
        self.label_convert.setObjectName("label_convert")
        self.verticalLayout_2.addWidget(self.label_convert)
        self.textEdit_convert = QtWidgets.QTextEdit(self.tr_frame)
        self.textEdit_convert.setObjectName("textEdit_convert")
        self.verticalLayout_2.addWidget(self.textEdit_convert)
        self.pushButton_clear_convert = QtWidgets.QPushButton(self.tr_frame)
        self.pushButton_clear_convert.setObjectName("pushButton_clear_convert")
        self.verticalLayout_2.addWidget(self.pushButton_clear_convert)
        self.mainlayout_1.addWidget(self.tr_frame)
        self.verticalLayout_6.addLayout(self.mainlayout_1)
        self.mainlayout_2 = QtWidgets.QVBoxLayout()
        self.mainlayout_2.setContentsMargins(5, 5, 5, 5)
        self.mainlayout_2.setSpacing(5)
        self.mainlayout_2.setObjectName("mainlayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_import = QtWidgets.QLabel(self.centralwidget)
        self.label_import.setMinimumSize(QtCore.QSize(60, 0))
        self.label_import.setIndent(5)
        self.label_import.setObjectName("label_import")
        self.horizontalLayout.addWidget(self.label_import)
        self.lineEdit_import_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_import_path.setObjectName("lineEdit_import_path")
        self.horizontalLayout.addWidget(self.lineEdit_import_path)
        self.toolButton_import_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_import_path.setObjectName("toolButton_import_path")
        self.horizontalLayout.addWidget(self.toolButton_import_path)
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.mainlayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_saveto = QtWidgets.QLabel(self.centralwidget)
        self.label_saveto.setMinimumSize(QtCore.QSize(60, 0))
        self.label_saveto.setIndent(5)
        self.label_saveto.setObjectName("label_saveto")
        self.horizontalLayout_2.addWidget(self.label_saveto)
        self.lineEdit_saveto_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_saveto_path.setObjectName("lineEdit_saveto_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_saveto_path)
        self.toolButton_saveto_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_saveto_path.setObjectName("toolButton_saveto_path")
        self.horizontalLayout_2.addWidget(self.toolButton_saveto_path)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.mainlayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.mainlayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.save_asAction = QtWidgets.QAction(MainWindow)
        self.save_asAction.setObjectName("save_asAction")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.copyAction = QtWidgets.QAction(MainWindow)
        self.copyAction.setObjectName("copyAction")
        self.pasteAction = QtWidgets.QAction(MainWindow)
        self.pasteAction.setObjectName("pasteAction")
        self.clearAction = QtWidgets.QAction(MainWindow)
        self.clearAction.setObjectName("clearAction")
        self.actionPreference = QtWidgets.QAction(MainWindow)
        self.actionPreference.setShortcut("")
        self.actionPreference.setObjectName("actionPreference")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actiontest.setObjectName("actiontest")
        self.menuFile.addAction(self.openAction)
        self.menuFile.addAction(self.saveAction)
        self.menuFile.addAction(self.save_asAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.clearAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_resource.setText(_translate("MainWindow", "Resource"))
        self.pushButton_clear_resource.setText(_translate("MainWindow", "Clear"))
        self.label_shiftLevel.setText(_translate("MainWindow", "Shift Level: "))
        self.pushButton_encode.setText(_translate("MainWindow", "»"))
        self.pushButton_decode.setText(_translate("MainWindow", "«"))
        self.label_convert.setText(_translate("MainWindow", "Convert"))
        self.pushButton_clear_convert.setText(_translate("MainWindow", "Clear"))
        self.label_import.setText(_translate("MainWindow", "Import: "))
        self.toolButton_import_path.setText(_translate("MainWindow", "..."))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.label_saveto.setText(_translate("MainWindow", "Save to: "))
        self.toolButton_saveto_path.setText(_translate("MainWindow", "..."))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.openAction.setText(_translate("MainWindow", "Open"))
        self.openAction.setToolTip(_translate("MainWindow", "Open and load the file to resource"))
        self.openAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveAction.setText(_translate("MainWindow", "Save"))
        self.saveAction.setToolTip(_translate("MainWindow", "Overwrite the current file"))
        self.saveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.save_asAction.setText(_translate("MainWindow", "Save as"))
        self.save_asAction.setToolTip(_translate("MainWindow", "Save as a new file"))
        self.save_asAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("MainWindow", "Exit"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.copyAction.setText(_translate("MainWindow", "Copy"))
        self.copyAction.setToolTip(_translate("MainWindow", "Copy text from convert"))
        self.copyAction.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pasteAction.setText(_translate("MainWindow", "Paste"))
        self.pasteAction.setToolTip(_translate("MainWindow", "Paste to the resource"))
        self.pasteAction.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.clearAction.setText(_translate("MainWindow", "Clear all"))
        self.clearAction.setToolTip(_translate("MainWindow", "Formate all cells"))
        self.clearAction.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionPreference.setText(_translate("MainWindow", "Preference"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest.setShortcut(_translate("MainWindow", "Meta+T"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
